### PR TITLE
Add ReactNativeUnifiedPlan handler

### LINKED ISSUE #221: Support react-native-webrtc  version 1.106 +
React-native-webrtc recently switched to the unified plan: https://github.com/react-native-webrtc/react-native-webrtc/releases The current handler just won't work with the new version.

### PR DESCRIPTION
**Pull request by ibc**
- Fixes #221

### Details

- This PR adds a new `ReactNativeUnifiedPlan` handler for latest version of react-native-webrtc module.
- The new `ReactNativeUnifiedPlan` handler is basically a copy&paste of `Chrome74` handler with a minor change required by react-native-webrtc (the `close()` method in `ReactNativeUnifiedPlan` handler calls `this._sendStream.release(/* releaseTracks */ false);`, same as in PlanB `ReactNative` old handler).

The new `ReactNativeUnifiedPlan` handler is automatically detected by `mediasoupClient.detectDevice()` in React Native environments if:

- [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc/) installed version is >= 106.0.0.
- [registerGlobals()](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BasicUsage.md#registering-globals) (exported by react-native-webrtc module) has been called before.
- If so, [detectDevice()](https://mediasoup.org/documentation/v3/mediasoup-client/api/#mediasoupClient-detectDevice) method in mediasoup-client will verify that `typeof RTCRtpTransceiver !== 'undefined'` and will select the new `ReactNativeUnifiedPlan` handler.

### TODO

As [announced](https://mediasoup.discourse.group/t/need-testers-for-reactnative-unified-plan/4739) in the forum we need testers (I cannot test it locally). Basically we need that people uses the latest react-native-webrtc 106.0.0-beta.7 and the branch `react-native-unified-plan` of this PR and verifies that everything works as expected:
- The detected handler is 'ReactNativeUnifiedPlan': `device.handlerName === 'ReactNativeUnifiedPlan'`.
- Creating multiple audio/video producers and consumers work fine.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Comment by jbaudanza** [comment]
I tested this PR in our app using `react-native-webrtc@106.0.0-beta.7`. Everything seems to work fine, except I occasionally see this warning in my react-native console when creating a transport.

```
 WARN  Sending `peerConnectionOnRenegotiationNeeded` with no listeners registered.
```

I didn't notice any negative side-effects from this. Maybe there's some kind of race-condition setting up an event listener somewhere.

Also, our app is audio-only so I wasn't able to test any video streams. Let me know if you'd like me to dig deeper on anything.

**Comment by ibc** [comment]
Such a warning is ok because indeed mediasoup-client doesn't subscribe to that event (no need for it). Thanks @jbaudanza

**Comment by charlyBerthet** [comment]
I was able to test it using the branch and it's working fine as well. WebRTC OK, Audio Stream OK, Video Stream OK. Tested only on ReactNative iOS under the same NAT network. (Broadcaster : RN iPhone ; Server : OSX ; Consumer : RN iPad)

**Comment by ibc** [comment]
Let's merge and release.

**Pull request merged**
