### PR TITLE
Handlers: ReactNative, fix concurrent track reception

### PR DESCRIPTION
**Pull request by jmillan**
Fix ReactNative handler wrong `streamId` usage.

### CODE REVIEW

**Review by ibc — COMMENTED** [review]
How is this NOT a problem also in other PlanB handlers such as Chrome56, Safari11 etc?

**Comment by jmillan** [comment]
> How is this NOT a problem also in other PlanB handlers such as Chrome56, Safari11 etc?

Looking at it

**Comment by jmillan** [comment]
Because this is React Native specific, where the `streamId` we create contains the suffix: **streamId += `-hack-${utils.generateRandomNumber()}`;**

Only needed there.

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
Release please

**Pull request merged**
