### PR TITLE
Better syntax for appData

### PR DESCRIPTION
**Pull request by ibc**

### CODE REVIEW

**Review by jmillan — APPROVED** [review]
:+1:

**Comment by unao** [comment]
Changing `any` to `Record<string, unknown>` is a breaking change. 

Not sure what exactly is the benefit of forcing  `Record<string, unknown>` of `appData` (and not simply `unknown`).  My understanding was `appData` is totally opaque for the mediasoup-client lib.

This could be improved substantially by specifying a generic type `A extends Record<string, unknown> = Record<string, unknown>` or imho even better `A = unknown`. Without having generic `appData` it is non-trivial to integrate this lib into a typescript codebase.

Actually I wanted to suggest these changes as I found them quite needed, but waiting for 3 months for this PR to be reviewed: https://github.com/versatica/mediasoup-client/pull/200

**Comment by ibc** [comment]
appData is defined as an object that ALWAYS exists and the app can just set string values with any value.

**Comment by unao** [comment]
I think more people see beneficial to have `appData` properly typed with generics: https://github.com/versatica/mediasoup/issues/832.

**Pull request merged**
