### PR TITLE
Handlers: add the ability to pause/resume Consumers concurrently

### PR DESCRIPTION
**Pull request by jmillan**
For the same reason we added concurrency for `handler.receive()`. Adding concurrency for pause/resume avoids multiple SDP renegotiation done one by one which can take a lot of time when there are many consumers.

### CODE REVIEW

**Comment by msach22** [comment]
Nice work 😄

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
Release?

**Comment by jmillan** [comment]
> Release?

Yes, done

**Comment by zhangshaoju1987** [comment]
This is so great ! 
Does react-native handler also support consumer concurrent?

**Pull request merged**
