### PR TITLE
tsconfig: use esModuleInterop:true to avoid import issues in bowser dependency

### LINKED ISSUE #159: Vite.js support
## Bug Report

Running with [Vite](https://vitejs.dev/) causes an issue:

```
Uncaught TypeError: bowser.getParser is not a function
    detectDevice Device.js:35
    Device Device.js:135
    <anonymous> main.ts:5
```

### Your environment

- Operating system: macOS M1
- Browser version: Firefox 
- npm version:  7.5.3
- mediasoup-client version: 3.6.28

### Issue description

1. Set up a vite project (vue + ts): `npm init @vitejs/app`
2. Install mediasoup client: `npm i mediasoup-client`
3. To `main.ts` add these lines:

```ts
import * as mediasoupClient from 'mediasoup-client'
let mediasoupDevice = new mediasoupClient.Device()
```

**Expected:** Should not throw error

**Actual:** Throws error. Probably related to Vite's strict ESM module handling.

### Related
- #88 
- https://github.com/lancedikson/bowser/issues/339
- https://vitejs.dev/guide/dep-pre-bundling.html#dependency-pre-bundling

### PR DESCRIPTION
**Pull request by ibc**
May fix #159 

**NOTE:** This must be properly tested to ensure that it does not break other environments.

### CODE REVIEW

**Comment by holtwick** [comment]
Thanks for looking into it.

This throws: `Uncaught SyntaxError: indirect export not found: ScalabilityMode types.ts:11:8` in Vite

**Comment by ibc** [comment]
Honestly no idea. Can you try https://vitejs.dev/config/#optimizedeps-exclude in your Vite app and use mediasoup-client v3 branch or NPM version? I'm afraid we cannot do magic in mediasoup-client to make all frameworks happy.

**Comment by holtwick** [comment]
I absolutely understand that supporting any exotic bundler is out of scope, but thanks a lot for still taking the time!

The last issue was fixed by changing:

```ts
export type { ScalabilityMode } from './scalabilityModes';
```

to

```ts
export type { ScalabilityMode } from './scalabilityModes';
```

I made a PR out of it #161

With this change Vite support would work in my trivial tests.

**Comment by ibc** [comment]
Everything seems to work. Merging in `v3` and releasing. Thanks.

**Comment by ibc** [comment]
Umm, not yet, sorry, re-testing.

**Comment by holtwick** [comment]
> Everything seems to work. Merging in `v3` and releasing. Thanks.

Thank you! And also thanks for creating the great mediasoup project!!!

**Comment by ibc** [comment]
mediasoup-client 3.6.29 published

**Pull request merged**
