### PR TITLE
Include local iceParameters in Transport 'connect' event

### PR DESCRIPTION
**Pull request by ibc**
To complement https://github.com/versatica/mediasoup/pull/1332.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Comment by ibc** [comment]
I'm redoing this because ICE related fields cannot be in `DtlsParameters`.

**Comment by ibc** [comment]
@jmillan I've redone this PR completely since it didn't make any sense.

**Comment by ibc** [comment]
Let's merge and release.

**Comment by ibc** [comment]
Reverted in 3.7.4 as discussed somewhere.

**Pull request merged**
