### PR TITLE
Build esm/commonjs using rollup

### PR DESCRIPTION
**Pull request by satoren**
Brushed up https://github.com/versatica/mediasoup-client/pull/260.

There are no more extras than with vite.

### CODE REVIEW

**Comment by ibc** [comment]
So can we close #260?

**Comment by ibc** [comment]
So I'm testing this. Some issues and concerns in next comments.

**Comment by ibc** [comment]
### Issue 1: `npm run typescript:watch` throws

```
$ npm run typescript:watch

> mediasoup-client@3.6.89 typescript:watch
> node npm-scripts.mjs typescript:watch
[2:37:36 PM] Starting compilation in watch mode...

[2:37:41 PM] Found 0 errors. Watching for file changes.

npm-scripts [INFO] [typescript:watch] replaceVersion()
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'lib/index.js'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at TscWatchClient.replaceVersion (file:///Users/ibc/src/v3-mediasoup-client/npm-scripts.mjs:129:19)
    at TscWatchClient.emit (node:events:513:28)
    at ChildProcess.<anonymous> (/Users/ibc/src/v3-mediasoup-client/node_modules/tsc-watch/dist/client/client.js:40:18)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:946:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'lib/index.js'
}
```

This is probably due to `noEmit: true` in `tsconfig.json`. Note that `typescript:watch` does not build the library but just relies on `tsc-watch` library:

```ts
		case 'typescript:watch':
		{
			// NOTE: Load dep on demand since it's a devDependency.
			const { TscWatchClient } = await import('tsc-watch/client.js');

			const watch = new TscWatchClient();

			deleteLib();

			watch.on('success', replaceVersion);
			watch.start('--pretty');

			break;
		}
```

And if I comment line `watch.on('success', replaceVersion);` then it doesn't throw... however it doesn't generate `lib` folder, so it's not useful at all for real-time testing (which I use extensively). To clarify: I run mediasoup-demo locally with `app/node_modules/mediasoup-client` being a soft link to my `mediasoup-client` folder. I run `npm run typescript:watch` to ensure that everytime I make a change in `mediasoup-client`, the demo app is reloaded. This no longer works using this ESM PR.

**Comment by ibc** [comment]
### Size concern

Generated `lib` folder by calling `npm run typescript`:

#### Using mediasoup-client v3 branch

```
-rw-r--r--   1 ibc  wheel   2.8K Jun 23 14:27 Consumer.d.ts
-rw-r--r--   1 ibc  wheel   2.3K Jun 23 14:27 Consumer.d.ts.map
-rw-r--r--   1 ibc  wheel   4.6K Jun 23 14:27 Consumer.js
-rw-r--r--   1 ibc  wheel   2.4K Jun 23 14:27 DataConsumer.d.ts
-rw-r--r--   1 ibc  wheel   1.9K Jun 23 14:27 DataConsumer.d.ts.map
-rw-r--r--   1 ibc  wheel   4.3K Jun 23 14:27 DataConsumer.js
-rw-r--r--   1 ibc  wheel   2.5K Jun 23 14:27 DataProducer.d.ts
-rw-r--r--   1 ibc  wheel   1.9K Jun 23 14:27 DataProducer.d.ts.map
-rw-r--r--   1 ibc  wheel   4.9K Jun 23 14:27 DataProducer.js
-rw-r--r--   1 ibc  wheel   3.4K Jun 23 14:27 Device.d.ts
-rw-r--r--   1 ibc  wheel   2.0K Jun 23 14:27 Device.d.ts.map
-rw-r--r--   1 ibc  wheel    18K Jun 23 14:27 Device.js
-rw-r--r--   1 ibc  wheel   1.4K Jun 23 14:27 EnhancedEventEmitter.d.ts
-rw-r--r--   1 ibc  wheel   1.8K Jun 23 14:27 EnhancedEventEmitter.d.ts.map
-rw-r--r--   1 ibc  wheel   2.0K Jun 23 14:27 EnhancedEventEmitter.js
-rw-r--r--   1 ibc  wheel   313B Jun 23 14:27 Logger.d.ts
-rw-r--r--   1 ibc  wheel   420B Jun 23 14:27 Logger.d.ts.map
-rw-r--r--   1 ibc  wheel   1.2K Jun 23 14:27 Logger.js
-rw-r--r--   1 ibc  wheel   4.3K Jun 23 14:27 Producer.d.ts
-rw-r--r--   1 ibc  wheel   3.6K Jun 23 14:27 Producer.d.ts.map
-rw-r--r--   1 ibc  wheel   8.1K Jun 23 14:27 Producer.js
-rw-r--r--   1 ibc  wheel   9.7K Jun 23 14:27 RtpParameters.d.ts
-rw-r--r--   1 ibc  wheel   2.6K Jun 23 14:27 RtpParameters.d.ts.map
-rw-r--r--   1 ibc  wheel   177B Jun 23 14:27 RtpParameters.js
-rw-r--r--   1 ibc  wheel   1.7K Jun 23 14:27 SctpParameters.d.ts
-rw-r--r--   1 ibc  wheel   783B Jun 23 14:27 SctpParameters.d.ts.map
-rw-r--r--   1 ibc  wheel    77B Jun 23 14:27 SctpParameters.js
-rw-r--r--   1 ibc  wheel   7.5K Jun 23 14:27 Transport.d.ts
-rw-r--r--   1 ibc  wheel   5.7K Jun 23 14:27 Transport.d.ts.map
-rw-r--r--   1 ibc  wheel    33K Jun 23 14:27 Transport.js
-rw-r--r--   1 ibc  wheel   341B Jun 23 14:27 errors.d.ts
-rw-r--r--   1 ibc  wheel   241B Jun 23 14:27 errors.d.ts.map
-rw-r--r--   1 ibc  wheel   1.1K Jun 23 14:27 errors.js
drwxr-xr-x  43 ibc  wheel   1.3K Jun 23 14:27 handlers/
-rw-r--r--   1 ibc  wheel   541B Jun 23 14:27 index.d.ts
-rw-r--r--   1 ibc  wheel   466B Jun 23 14:27 index.d.ts.map
-rw-r--r--   1 ibc  wheel   2.1K Jun 23 14:27 index.js
-rw-r--r--   1 ibc  wheel   5.0K Jun 23 14:27 ortc.d.ts
-rw-r--r--   1 ibc  wheel   1.9K Jun 23 14:27 ortc.d.ts.map
-rw-r--r--   1 ibc  wheel    34K Jun 23 14:27 ortc.js
-rw-r--r--   1 ibc  wheel   210B Jun 23 14:27 scalabilityModes.d.ts
-rw-r--r--   1 ibc  wheel   272B Jun 23 14:27 scalabilityModes.d.ts.map
-rw-r--r--   1 ibc  wheel   555B Jun 23 14:27 scalabilityModes.js
drwxr-xr-x  11 ibc  wheel   352B Jun 23 14:27 tests/
-rw-r--r--   1 ibc  wheel   462B Jun 23 14:27 types.d.ts
-rw-r--r--   1 ibc  wheel   443B Jun 23 14:27 types.d.ts.map
-rw-r--r--   1 ibc  wheel   1.2K Jun 23 14:27 types.js
-rw-r--r--   1 ibc  wheel   239B Jun 23 14:27 utils.d.ts
-rw-r--r--   1 ibc  wheel   233B Jun 23 14:27 utils.d.ts.map
-rw-r--r--   1 ibc  wheel   533B Jun 23 14:27 utils.js
```

Total size: **1.0 MB**


#### Using esm/commonjs branch

```
-rw-r--r--  1 ibc  wheel    45K Jun 23 14:32 index.d.ts
-rw-r--r--  1 ibc  wheel   375K Jun 23 14:32 index.js
-rw-r--r--  1 ibc  wheel   840K Jun 23 14:32 index.js.map
-rw-r--r--  1 ibc  wheel   374K Jun 23 14:32 index.mjs
-rw-r--r--  1 ibc  wheel   840K Jun 23 14:32 index.mjs.map
```

Total size: **2.4 MB**

So it's 2.4 MB vs 1.0 MB ¿¿¿???

**Comment by ibc** [comment]
I'm forked this PR and made some changes to fix things:

https://github.com/versatica/mediasoup-client/pull/272

My concern is still the size of the generated `lib` folder which is 2.4x higher than in v3 branch.

**Comment by nazar-pc** [comment]
There are two outputs: js and mjs, which is ~2x already

**Comment by ibc** [comment]
> There are two outputs: js and mjs, which is ~2x already

So pros:

- Being build with rollup we provide better loading choices for the app, which would lead to smaller **app** bundles.

Consts:

- Size of the mediasoup-client NPM library is way bigger.

Is it ok then?

**Comment by satoren** [comment]
https://github.com/versatica/mediasoup-client/pull/272

**Pull request closed without merging**
