### PR TITLE
bug fix：some exception on handle.receive().

### PR DESCRIPTION
**Pull request by brainwith**
without mid in rtpParameters (this always happend on older mediasoup). When we use multiple audio or video consumers on a single receive transport(UnifiedPlan mode), If we call internalHandler.Receive() and internalHandler.StopReceiving() in multiple times, then internalHandler.receive() will throw an exception. The reason is that multiple calls will lead to disorder of mid, which makes RemoteSdp.receive() incorrectly judge to use PlanB in , resulting in receive exception

### CODE REVIEW

**Comment by jmillan** [comment]
@brainwith,

Can you please provide some debug logs showing the issue?

**Comment by brainwith** [comment]
no problem! 
let me think,to recurrence the bug process is very long, it is difficult to make a brief description

**Comment by brainwith** [comment]
@jmillan  here's the debug log:

```
// consume audio
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=0, rtpParameters.mid=undefined, this._mapMidTransceiver[size=0, keys=[]] +0ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=0, this._midToIndex.keys=[], this._mediaSections.length=0 mediaSection.closed=undefined +0ms
mediasoup-client:RemoteSdp [trace bug]leave receive(): mid=0, this._midToIndex.keys=[0], this._mediaSections.length=1 mediaSection.closed=false +1ms
mediasoup-client:Chrome74 [trace bug]leave receive(): localId=0, rtpParameters.mid=undefined, this._mapMidTransceiver[size=1, keys=[0]] +2ms

// consume video(v1)
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=1, rtpParameters.mid=undefined, this._mapMidTransceiver[size=1, keys=[0]] +0ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=1, this._midToIndex.keys=[0], this._mediaSections.length=1 mediaSection.closed=undefined +46ms
mediasoup-client:RemoteSdp [trace bug]leave receive(): mid=1, this._midToIndex.keys=[0,1], this._mediaSections.length=2 mediaSection.closed=false +1ms
mediasoup-client:Chrome74 [trace bug]leave receive(): localId=1, rtpParameters.mid=undefined, this._mapMidTransceiver[size=2, keys=[0,1]] +1ms

// consume video(probator)
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=probator, rtpParameters.mid=probator, this._mapMidTransceiver[size=2, keys=[0,1]] +0ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=probator, this._midToIndex.keys=[0,1], this._mediaSections.length=2 mediaSection.closed=undefined +8ms
mediasoup-client:RemoteSdp [trace bug]leave receive(): mid=probator, this._midToIndex.keys=[0,1,probator], this._mediaSections.length=3 mediaSection.closed=false +0ms
mediasoup-client:Chrome74 [trace bug]leave receive(): localId=probator, rtpParameters.mid=probator, this._mapMidTransceiver[size=3, keys=[0,1,probator]] +1ms

// consume.close() video(v1)
mediasoup-client:Chrome74 [trace bug]enter stopReceiving(): localId=1, this._mapMidTransceiver[size=3, keys=[0,1,probator]] +0ms
mediasoup-client:Chrome74 [trace bug]leave stopReceiving(): localId=1, this._mapMidTransceiver[size=2, keys=[0,probator]] +3ms

// consume video(v2)
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=2, rtpParameters.mid=undefined, this._mapMidTransceiver[size=2, keys=[0,probator]] +1ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=2, this._midToIndex.keys=[0,1,probator], this._mediaSections.length=3 mediaSection.closed=undefined +24s
mediasoup-client:RemoteSdp [trace bug]leave receive(): mid=2, this._midToIndex.keys=[0,probator,2], this._mediaSections.length=3 mediaSection.closed=false +1ms
mediasoup-client:Chrome74 [trace bug]leave receive(): localId=2, rtpParameters.mid=undefined, this._mapMidTransceiver[size=3, keys=[0,probator,2]] +10ms

// consume video(v1)
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=3, rtpParameters.mid=undefined, this._mapMidTransceiver[size=3, keys=[0,probator,2]] +1ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=3, this._midToIndex.keys=[0,probator,2], this._mediaSections.length=3 mediaSection.closed=undefined +8s
mediasoup-client:RemoteSdp [trace bug]leave receive(): mid=3, this._midToIndex.keys=[0,probator,2,3], this._mediaSections.length=4 mediaSection.closed=false +1ms
mediasoup-client:Chrome74 [trace bug]leave receive(): localId=3, rtpParameters.mid=undefined, this._mapMidTransceiver[size=4, keys=[0,probator,2,3]] +3ms

// consume.close() video(v1)
mediasoup-client:Chrome74 [trace bug]enter stopReceiving(): localId=3, this._mapMidTransceiver[size=4, keys=[0,probator,2,3]] +0ms
mediasoup-client:Chrome74 [trace bug]leave stopReceiving(): localId=3, this._mapMidTransceiver[size=3, keys=[0,probator,2]] +4ms

// consume video(v1)--exception
mediasoup-client:Chrome74 [trace bug]enter receive(): localId=3, rtpParameters.mid=undefined, this._mapMidTransceiver[size=3, keys=[0,probator,2]] +1ms
mediasoup-client:RemoteSdp [trace bug]enter receive(): mid=3, this._midToIndex.keys=[0,probator,2,3], this._mediaSections.length=4 mediaSection.closed=true +11s
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
    at OfferMediaSection.planBReceive (MediaSection.js:483:1)
    at RemoteSdp.receive (RemoteSdp.js:176:1)
    at Chrome74.receive (Chrome74.js:419:1)
    at Object.transport.consume() [as task] (Transport.js:349:1)
    at AwaitQueue.<anonymous> (index.js:144:1)
    at Generator.next (<anonymous>)
    at index.js:15:1
    at new Promise (<anonymous>)
    at __awaiter (index.js:11:1)
    at AwaitQueue.executeTask (index.js:138:1)
```

**Comment by jmillan** [comment]
Thanks for the info @brainwith.

**Comment by ibc** [comment]
I fail to see why we need these changes. Consumer creation and closure are enqueued actions that happen sequentially so there shouldn't be any chance for the reported issue to happen. I've inspected yet the provided logs. @jmillan any thoughts?

**Comment by ibc** [comment]
How is it possible that Chrome74 (which uses Unified-Plan) is calling this method?

`OfferMediaSection.planBReceive()`

**Comment by jmillan** [comment]
I think I'm seeing the issue. Let me verify.

**Comment by jmillan** [comment]
Ongoing fix.

**Comment by jmillan** [comment]
@brainwith, a new version has been released with the corresponding fix.

Thanks for noticing!

**Comment by brainwith** [comment]
> @brainwith, a new version has been released with the corresponding fix.
> 
> Thanks for noticing!

hi @jmillan , #196 after i tested it, i found that the bug was not fixed 
store localId is not the solution,there are two main reasons for this bug:
 1. wrong localId generate:  
         wrong : const localId = rtpParameters.mid || String(this._mapMidTransceiver.size);
         correct：
                         const nextMSid = this._remoteSdp!.getNextMediaSectionIdx();
			const localId = rtpParameters.mid || nextMSid.reuseMid || String(nextMSid.idx);
 2. wrong conditional judgment：in UnifiedPlan mode, mediaSection may not be undefined 
         wrong:  
                 // Unified-Plan or different media kind.
		if ( !mediaSection ){ }
		// Plan-B.
		else{  } 
        correct: 
                 // Unified-Plan or different media kind.
		if ( !mediaSection **|| (!this._planB && mediaSection.closed)** ){ }
		// Plan-B.
		else{  }

**Comment by brainwith** [comment]
> I fail to see why we need these changes. Consumer creation and closure are enqueued actions that happen sequentially so there shouldn't be any chance for the reported issue to happen. I've inspected yet the provided logs. @jmillan any thoughts?

hi @ibc ,
this can happend when we use three consumers at the same time on a receive transport: audio(mic), video1(camera), video2(deskshare); then the consumer's producer switch video1(camera).
mediasoup-demo seem do not provide this kind of situation,because camera and deskshare are mutually exclusive.

**Comment by jmillan** [comment]
I'll check this in few hours

**Pull request closed without merging**
